AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master stack for nested VPC and EC2 stacks'

Parameters:
  KeyPairName:
    Type: String
    Default: 'ekskp1'
    Description: EC2 Key Pair name
  
  InstanceType:
    Type: String
    Default: 't2.micro'
    Description: EC2 instance type

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWS::Region}.amazonaws.com/cfn-templates/vpc-stack.yaml'
      Parameters:
        VpcCidr: '10.0.0.0/16'
        PublicSubnetCidr: '10.0.1.0/24'
      Tags:
        - Key: Name
          Value: VPC-NestedStack

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub 'https://${AWS::Region}.amazonaws.com/cfn-templates/ec2-stack.yaml'
      Parameters:
        VpcStackName: !Ref VPCStack
        KeyPairName: !Ref KeyPairName
        InstanceType: !Ref InstanceType
      Tags:
        - Key: Name
          Value: EC2-NestedStack

Outputs:
  VpcId:
    Description: VPC ID from nested stack
    Value: !GetAtt VPCStack.Outputs.VpcId
  
  EC2InstanceId:
    Description: EC2 Instance ID from nested stack
    Value: !GetAtt EC2Stack.Outputs.InstanceId
  
  EC2PublicIP:
    Description: EC2 Public IP from nested stack
    Value: !GetAtt EC2Stack.Outputs.PublicIP